### ISSUE TITLE
Text wrap issues on contract details modal

### ISSUE THREAD

**Issue by Dev-JamesR** [Ether1Project/ethofs-upload-dashboard#10]

**Comment by fallengravity** [comment]
Please, may I have screenshot - I would like to make sure I'm fixing the correct thing

**Comment by Dev-JamesR** [comment]
![image](https://user-images.githubusercontent.com/39209383/66066261-0f3d1c00-e4fe-11e9-8538-a37044b85228.png)

**Comment by Dev-JamesR** [comment]
Description is being pulled in incorrectly but both description and hash should either wrap or scroll

**Comment by Dev-JamesR** [comment]
It looks good now, must've had cache issue or you just fixed
