### ISSUE TITLE
Uploading from mobile

### ISSUE THREAD

**Issue by Primate411** [Ether1Project/ethofs-upload-dashboard#11]
When trying to use https://ethofs.com/uploads.html from mobile, user gets private key notification, after private key notification, it presents username notification.  After username is entered in, it says address not found - user not found.

Refreshing the page presents the user with private key > username prompt again, looking like username doesn't get registered properly

**Comment by Dev-JamesR** [comment]
Can you reproduce and add a screenshot of the console/log output? It registers for me on mobile.
