### ISSUE TITLE
Node Count Via API

### ISSUE THREAD

**Issue by fallengravity** [Ether1Project/ethofs-upload-dashboard#12]
We need to pull node count in via the api instead of relying on IPFS for the data.

**Comment by insxnic** [comment]
> That’s not correct, it’s just the number that is reporting/reachable via pubsub from the local browser node, when we roll out the node updates we’ll work on stats reporting because the updated version of ipfs implements something called gossipsub and relays which allows for nodes to bounce messaging off one another in search of other nodes

**Comment by fallengravity** [comment]
> That’s not correct, it’s just the number that is reporting/reachable via pubsub from the local browser node, when we roll out the node updates we’ll work on stats reporting because the updated version of ipfs implements something called gossipsub and relays which allows for nodes to bounce messaging off one another in search of other nodes
