### ISSUE TITLE
Multiple uploads from mobile device 

### ISSUE THREAD

**Issue by fallengravity** [Ether1Project/ethofs-upload-dashboard#13]
Multiple Uploads from a mobile device - it will only show 1 file instead of the directory. 

> I'm gonna have it detect a Mobile os and switch to multi-file selection rather than a directory. The js directory input is what is breaking the code on mobile.

**Comment by Dev-JamesR** [comment]
Detection for mobile os/multi file upload selection has been implemented. When mobile os is detected the upload method will default to multiple file selection to make photo uploads easier to use.
