### ISSUE TITLE
Need to adjust modals to all match

### ISSUE THREAD

**Issue by fallengravity** [Ether1Project/ethofs-upload-dashboard#2]
Current modals all have different styles, Need to adjust them to be in line with the current theme

**Comment by fallengravity** [comment]
Contract details modal fixed in https://github.com/Ether1Project/ethofs-upload-dashboard/commit/25e251e97ab666e619eedb67df3010d313ccdaf4

**Comment by Dev-JamesR** [comment]
Should we make all modals have same background/color scheme? Currently login/node modals have a red/pink bg while block tracker, uploads status' have black. Also we should make all fonts the same, message logging in modals should be same/similar to test of fonts/boldness

**Comment by fallengravity** [comment]
I will fix up background and colors for sure, I will look at the fonts too, it is not something I really notice but I can imagine it can affect the User Experience. Looking right now at a mobile-friendly version of the:
``` Live Upload | ethoFS Browser Node Modal ```

**Comment by fallengravity** [comment]
For the most part, everything is pretty clean now, especially on the mobile end, there is definitely a little work left to be done with respect to fonts, etc. I am going to close this issue for now though as I believe this is decent enough for a release & usage. We will begin to further refine this once we've released it & gotten feedback
